# Generated by Django 4.1 on 2022-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_send_xodimlar_delete_xabar_yuborish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('matn', models.TextField()),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Send',
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='malumot',
            field=models.TextField(),
        ),
    ]
